---
- hosts: all

  pre_tasks:
    - name: Update apt cache if needed
      become: yes
      apt: update_cache=yes cache_valid_time=86400
    - name: Remove old app
      become: yes
      file:
        state: absent
        path: /srv/app
    - name: Verify that the deployment key is present
      copy:
        src: /Users/andresgz/keys/deployment
        dest: /home/ubuntu/.ssh/deployment
        mode: 0400

  tasks:
    - include_vars: system_requirements.yml
    - name: Install system packages.
      become: yes
      apt: name={{ item }} state=present
      with_items: system_requirements

    - name: Copy nginx config file
      become: yes
      copy:
        src: config_files/nginx
        dest: /etc/nginx/sites-available/nginx
    - name: Copy uwsgi config file
      become: yes
      copy:
        src: config_files/uwsgi.ini
        dest: /etc/uwsgi/apps-available/uwsgi.ini
    - name: Create symlink for nginx
      become: yes
      file:
        src: /etc/nginx/sites-available/nginx
        dest: /etc/nginx/sites-enabled/nginx
        state: link
    - name: Create symlink for uwsgi
      become: yes
      file:
        src: /etc/uwsgi/apps-available/uwsgi.ini
        dest: /etc/uwsgi/apps-enabled/uwsgi.ini
        state: link
    - name: Disable default nginx site
      become: yes
      file:
        dest: /etc/nginx/sites-enabled/default
        state: absent

    - name: Creates virtualenv.
      command: >
        virtualenv /home/ubuntu/.envs/idk
        creates="/home/ubuntu/.envs/idk"

    - name: Make sure that target directory exists
      become: yes
      file:
        path: /srv/app 
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Clone repository
      git: 
        repo: ssh://git@github.com/swappsco/pozting.git
        dest: /srv/app
        key_file: /home/ubuntu/.ssh/deployment
        accept_hostkey: yes
        depth: 1
        version: "{{ repo_tag  }}"

    - name: Install python requirements
      pip:
        requirements: /srv/app/requirements/production.txt
        virtualenv: /home/ubuntu/.envs/idk

    - name: Copy application config file
      copyv:
        src: ./env
        dest: /srv/app/.env

    - name: Restart uwsgi
      become: yes
      service: name=uwsgi state=reloaded

