---
- hosts: all


  pre_tasks:
    - name: Update apt cache if needed
      become: yes
      apt: update_cache=yes cache_valid_time=86400

  tasks:
    - include_vars: system_requirements.yml
    - name: Install system packages.
      become: yes
      apt: name={{ item }} state=present
      with_items: system_requirements
    - name: Creates virtualenv.
      command: >
        virtualenv /home/ubuntu/.envs/idk
        creates="/home/ubuntu/.envs/idk"
    - pip: requirements="/srv/apps/idk/requirements/production.txt" virtualenv="/home/ubuntu/.envs/idk"
