---
- hosts: all

  pre_tasks:
    - name: Update apt cache if needed
      become: yes
      apt: update_cache=yes cache_valid_time=86400
    - name: Verify that the deployment key is present
      copy:
        src: ~/.ssh/deployment
        dest: ~/.ssh/deployment
        mode: 0400

  roles:
    - requirements
    - nginx
    - django_setup

  handlers:
    - name: Install python requirements
      pip:
        requirements: /srv/apps/{{ app_name }}/requirements/production.txt
        virtualenv: ~/.envs/{{ app_name }}

    - name: Sync DB
      django_manage:
        command: migrate
        app_path: /srv/apps/{{ app_name }}/
        virtualenv: ~/.envs/{{ app_name }}
        settings: config.settings.production

    - name: Collect Static
      django_manage:
        command: collectstatic
        app_path: /srv/apps/{{ app_name }}/
        virtualenv: ~/.envs/{{ app_name }}
        settings: config.settings.production

    - name: Restart uwsgi
      become: yes
      service: name=uwsgi state=restarted

    - name: Restart nginx
      become: yes
      service: name=nginx state=reloaded

    - name: Deploy scraper
      shell: scrapyd-deploy qscraper
      when: app_name == "qscraper_prod" or app_name == "qscraper_dev"
