---
- hosts: all

  pre_tasks:
    - name: Update apt cache if needed
      become: yes
      apt: update_cache=yes cache_valid_time=86400
    - name: Verify that the deployment key is present
      copy:
        src: ~/.ssh/deployment
        dest: /home/ubuntu/.ssh/deployment
        mode: 0400

  tasks:
    - include_vars: system_requirements.yml

    - name: Install system packages.
      become: yes
      apt: name={{ item }} state=present
      with_items: system_requirements

    - name: Copy SSL files
      become: yes
      copy:
        src: ssl
        dest: /home/ubuntu

    - name: Copy Default nginx config file
      become: yes
      copy:
        src: config_files/nginx_default
        dest: /etc/nginx/sites-available/default

    - name: Copy nginx config file
      become: yes
      template:
        src: config_files/nginx
        dest: /etc/nginx/sites-available/nginx

    - name: Copy uwsgi config file
      become: yes
      template:
        src: config_files/uwsgi.ini
        dest: /etc/uwsgi/apps-available/{{ app_name }}.ini

    - name: Create symlink for nginx default
      become: yes
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify:
      - Restart nginx

    - name: Create symlink for nginx
      become: yes
      file:
        src: /etc/nginx/sites-available/nginx
        dest: /etc/nginx/sites-enabled/nginx
        state: link
      notify:
      - Restart nginx

    - name: Create symlink for uwsgi
      become: yes
      file:
        src: /etc/uwsgi/apps-available/{{ app_name }}.ini
        dest: /etc/uwsgi/apps-enabled/{{ app_name }}.ini
        state: link

    - name: Creates virtualenv.
      command: >
        virtualenv /home/ubuntu/.envs/{{ app_name }}
        creates="/home/ubuntu/.envs/{{ app_name }}"

    - name: Make sure that target directory exists
      become: yes
      file:
        path: /srv/apps/{{ app_name }} 
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Clone repository
      git: 
        repo: "{{ repo_url }}"
        dest: /srv/apps/{{ app_name }}
        key_file: /home/ubuntu/.ssh/deployment
        accept_hostkey: yes
        version: "{{ repo_tag  }}"
        force: yes
        update: yes
      notify:
      - Install python requirements
      - Sync DB
      - Collect Static
      - Restart uwsgi


    - name: Copy application config file
      copyv:
        src: ./envs/{{ app_name }}
        dest: /srv/apps/{{ app_name }}/.env
      notify:
      - Restart uwsgi


  handlers:
    - name: Install python requirements
      pip:
        requirements: /srv/apps/{{ app_name }}/requirements/production.txt
        virtualenv: /home/ubuntu/.envs/{{ app_name }}

    - name: Sync DB
      django_manage:
        command: migrate
        app_path: /srv/apps/{{ app_name }}/
        virtualenv: /home/ubuntu/.envs/{{ app_name }}
        settings: config.settings.production

    - name: Collect Static
      django_manage:
        command: collectstatic
        app_path: /srv/apps/{{ app_name }}/
        virtualenv: /home/ubuntu/.envs/{{ app_name }}
        settings: config.settings.production

    - name: Restart uwsgi
      become: yes
      service: name=uwsgi state=restarted

    - name: Restart nginx
      become: yes
      service: name=nginx state=reloaded

