---

- hosts: all

  roles:
  #- Stouts.python
  - build-essential

  roles:
    - install_pip
    - requirements
    - nginx
    - django_setup

  handlers:

    - name: Deploy scraper
      shell: scrapyd-deploy qscraper
      when: app_name == "qscraper_prod" or app_name == "qscraper_dev"
