---

- name: Collect Static
  django_manage:
    command: collectstatic
    app_path: /srv/apps/{{ app_name }}/
    virtualenv: ~/.envs/{{ app_name }}
    settings: config.settings.production

- name: Restart uwsgi
  become: yes
  service: name=uwsgi state=restarted