---
  - name: Update apt cache if needed
    become: yes
    apt: update_cache=yes cache_valid_time=86400
  - name: Verify that the deployment key is present
    copy:
      src: ~/.ssh/deployment
      dest: ~/.ssh/deployment
      mode: 0400
